spring:
  datasource:
    url: jdbc:mysql://localhost:13306/paneldb?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  liquibase:
    enabled: false

logging:
  level:
    org:
      jooq: DEBUG
